---

- hosts: all
  become: true
  tasks:

  
  - name: update repository
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
  - name: install apache2 package
    apt:
      name: apache2
    when: ansible_distribution == "Ubuntu"
  - name: Ajouter le support php pour apache
    apt:
      name: libapache2-mod-php
    when: ansible_distribution == "Ubuntu"
