---


- hosts: all
  become: true
  pre_tasks:


  - name: install apache2 package
    apt:
      name:
        - apache2
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"
    register: result

  - name: essaye de redémarrer le service apache 2 Après une installation
    tags: restart,apache2
    service:
      name: apache2
      state: restarted
    when: result.changed == false


  - name: Edit Security File In Order To Test This Fonctionnalité
    tags: change,file,content
    lineinfile:
        path: /etc/apache2/apache2.conf
        regexp: '^Timeout'
        line: 'Timeout 500'
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for other servers.
    tags: apache,apache2,httpd
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

  - name: copy css style tous les serveurs
    tags: copy syles css into each servers
    copy:
      src: styles.css
      dest: /var/www/html/styles.css
      owner: root
      group: root
      mode: 0644




- hosts: all
  become: true
  tasks:

  - name: create a new user Isam
    tags: always
    user:
      name: Isam
      groups: root

  - name: add ssh key for  Isam
    tags: always
    authorized_key:
      user: Isam
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD4kcmhgwxJkKNugDRHSruoAEpXXw35eBGzS7t8vWFY6SOaiEZRHiquX47a2HZh+2PbNlT3MBFnD9dX4d66bLVI0qEh4bHHIx+POgTXQSE1Hzij5oIvIUDf3XbRco0VXWaZas6IypnTsCvC2BskD9q1bdXSovh3FOkFefzFJ8nssihCl4iybzqBANa19RPLS31udOuMr0rSJk3BLJWpnNjd55rRHGNwv6Cya5+Csu4pzqCTGNO5q1d7Uu7zbBvc/4NN5lgkW8tzVyYFtQQ6/0qvvmPWZC9tPjZqbnB0k8ctK49MaOfQhjvV+GH8d0IHOO/KhwhJQfJr6fkXmTVmjcqtoyQBTW+5MfSBINsNPYM5W9kJswnQRwCP+/1lLlDcIrbsYT1Ozu2NNMDO2lfAyThlRCUQypFRDeznfjcPUW5AySc/Q7k8ViuAcFCC+1HFyxIXSlu5z4EFVKajejI0i5m4Iv4l2SnNg22e4exeh5Ib6lBm80glkbWZxANjbD9mCVs= root@Ansible1"


- hosts: web_servers
  become: true
  tasks:

  - name: install php package
    tags: webserver,apache2lib,phppackage
    apt:
      name:
        - libapache2-mod-php

      state: latest

  - name: start web  server and interact with them
    tags: start,apache onobunto
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"




- hosts: db_servers
  become: true
  tasks:

  - name: install data base server package
    tags: db,mariadb,ubunto
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

